// <auto-generated />
using System;
using CoffeeShopDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopDAL.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20260210151431_data seeding")]
    partial class dataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopDAL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("EmailCheck", "Email Like '_%@_%._%'");

                            t.HasCheckConstraint("PhoneCheck", "PhoneNumber LIKE '01%' AND PhoneNumber NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VoucherId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.CartItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Image = "coffee.jpg",
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 8,
                            Image = "tea.jpg",
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 9,
                            Image = "dessert.jpg",
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 10,
                            Image = "bakery.jpg",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 11,
                            Image = "drinks.jpg",
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductSize")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "Strong black coffee",
                            Image = "espresso.jpg",
                            Name = "Espresso",
                            Price = 50m,
                            ProductSize = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Description = "Coffee with milk",
                            Image = "latte.jpg",
                            Name = "Latte",
                            Price = 120m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Description = "Coffee with foam",
                            Image = "cappuccino.jpg",
                            Name = "Cappuccino",
                            Price = 130m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            Description = "Diluted espresso",
                            Image = "americano.jpg",
                            Name = "Americano",
                            Price = 90m,
                            ProductSize = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Description = "Chocolate coffee",
                            Image = "mocha.jpg",
                            Name = "Mocha",
                            Price = 100m,
                            ProductSize = 3
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            Description = "Healthy green tea",
                            Image = "green_tea.jpg",
                            Name = "Green Tea",
                            Price = 50m,
                            ProductSize = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Description = "Classic black tea",
                            Image = "black_tea.jpg",
                            Name = "Black Tea",
                            Price = 30m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            Description = "Relaxing herbal tea",
                            Image = "chamomile_tea.jpg",
                            Name = "Chamomile Tea",
                            Price = 60m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            Description = "Refreshing mint tea",
                            Image = "mint_tea.jpg",
                            Name = "Mint Tea",
                            Price = 40m,
                            ProductSize = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "Flavored black tea",
                            Image = "earl_grey.jpg",
                            Name = "Earl Grey",
                            Price = 70m,
                            ProductSize = 3
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            Description = "Creamy cheesecake",
                            Image = "cheesecake.jpg",
                            Name = "Cheesecake",
                            Price = 250m,
                            ProductSize = 2,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 9,
                            Description = "Rich chocolate brownie",
                            Image = "brownie.jpg",
                            Name = "Chocolate Brownie",
                            Price = 150m,
                            ProductSize = 1,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 9,
                            Description = "French macaron",
                            Image = "macaron.jpg",
                            Name = "Macaron",
                            Price = 120m,
                            ProductSize = 1,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 9,
                            Description = "Italian dessert",
                            Image = "tiramisu.jpg",
                            Name = "Tiramisu",
                            Price = 280m,
                            ProductSize = 3,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            Description = "Vanilla cupcake",
                            Image = "cupcake.jpg",
                            Name = "Cupcake",
                            Price = 100m,
                            ProductSize = 1,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 10,
                            Description = "French bread",
                            Image = "baguette.jpg",
                            Name = "Baguette",
                            Price = 50m,
                            ProductSize = 3,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 10,
                            Description = "Buttery croissant",
                            Image = "croissant.jpg",
                            Name = "Croissant",
                            Price = 80m,
                            ProductSize = 2,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 10,
                            Description = "Sweet donut",
                            Image = "donut.jpg",
                            Name = "Donut",
                            Price = 150m,
                            ProductSize = 1,
                            Quantity = 400
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 10,
                            Description = "Blueberry muffin",
                            Image = "muffin.jpg",
                            Name = "Muffin",
                            Price = 70m,
                            ProductSize = 1,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 10,
                            Description = "Soft bread roll",
                            Image = "bread_roll.jpg",
                            Name = "Bread Roll",
                            Price = 40m,
                            ProductSize = 2,
                            Quantity = 350
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 11,
                            Description = "Freshly squeezed",
                            Image = "orange_juice.jpg",
                            Name = "Orange Juice",
                            Price = 100m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 11,
                            Description = "Refreshing lemonade",
                            Image = "lemonade.jpg",
                            Name = "Lemonade",
                            Price = 80m,
                            ProductSize = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 11,
                            Description = "Sting",
                            Image = "sting.jpg",
                            Name = "Coca Cola",
                            Price = 60m,
                            ProductSize = 3
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 11,
                            Description = "Orange soda",
                            Image = "fanta.jpg",
                            Name = "Fanta",
                            Price = 60m,
                            ProductSize = 3
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 11,
                            Description = "Kiwi Juice",
                            Image = "kiwi_juice.jpg",
                            Name = "Mineral Water",
                            Price = 150m,
                            ProductSize = 1
                        });
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumCartTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.ApplicationUser", b =>
                {
                    b.OwnsOne("CoffeeShopDAL.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("BuildingNumber")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Cart", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("CoffeeShopDAL.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopDAL.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.CartItem", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopDAL.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Order", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.OrderItem", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopDAL.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Product", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoffeeShopDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CoffeeShopDAL.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
